version: '3.9'

services:
  bot:
    image: 'globidocker/globibot'

    command: ['/globibot']

    environment:
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
      APPLICATION_ID: '${APPLICATION_ID}'

      SUBSCRIBER_ADDR: '0.0.0.0:4242'
      RPC_ADDR: '0.0.0.0:4243'

      RUST_LOG: 'globibot_bot=debug'

  plugin-openai:
    image: 'globidocker/globibot'

    depends_on: bot

    command: ['/plugins/openai']

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

  plugin-rateme:
    image: 'globidocker/globibot'

    depends_on: bot

    command: ['/plugins/rateme']

    volumes:
      - '${RATEME_IMG_PATH}:/imgs'

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

      RATEME_IMG_PATH: '/imgs'

  plugin-tuck:
    image: 'globidocker/globibot'

    depends_on: bot

    command: ['/plugins/tuck']

    volumes:
      - '${TUCK_IMG_PATH}:/imgs'

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

      TUCK_IMG_PATH: '/imgs'
      TUCK_COMMAND_ID: '${TUCK_COMMAND_ID}'

      RUST_LOG: 'globibot_plugin_tuck=debug'
