version: '3.9'

services:
  bot:
    image: 'globidocker/globibot'

    command: ['/globibot']

    environment:
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
      APPLICATION_ID: '${APPLICATION_ID}'

      SUBSCRIBER_ADDR: '0.0.0.0:4242'
      RPC_ADDR: '0.0.0.0:4243'

      RUST_LOG: 'globibot_bot=debug'

  plugin-openai:
    image: 'globidocker/globibot'

    command: ['/plugins/openai']

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

  plugin-rateme:
    image: 'globidocker/globibot'

    command: ['/plugins/rateme']

    volumes:
      - '${RATEME_IMG_PATH}:/imgs'

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

      RATEME_IMG_PATH: '/imgs'
      RATEME_COMMAND_ID: '${RATEME_COMMAND_ID}'

  plugin-tuck:
    image: 'globidocker/globibot'

    command: [
      '/plugins/tuck',
      # '--update-slash-cmd',
    ]

    volumes:
      - '${TUCK_IMG_PATH}:/imgs'

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

      TUCK_IMG_PATH: '/imgs'
      TUCK_COMMAND_ID: '${TUCK_COMMAND_ID}'

      RUST_LOG: 'globibot_plugin_tuck=debug'

  plugin-slap:
    image: 'globidocker/globibot'

    command: [
      '/plugins/slap',
    ]

    volumes:
      - '${SLAP_IMG_PATH}:/imgs'

    environment:
      SUBSCRIBER_ADDR: 'bot:4242'
      RPC_ADDR: 'bot:4243'

      SLAP_IMG_PATH: '/imgs'
      SLAP_COMMAND_ID: '${SLAP_COMMAND_ID}'

      RUST_LOG: 'globibot_plugin_slap=debug'


  # plugin-lang-detect:
  #   image: 'globidocker/globibot'

  #   command: ['/plugins/lang-detect']

  #   environment:
  #     SUBSCRIBER_ADDR: 'bot:4242'
  #     RPC_ADDR: 'bot:4243'

  #     LANG_DETECT_API_KEY: '${LANG_DETECT_API_KEY}'
  #     LANG_DETECT_ENABLED_CHANNELS: '${LANG_DETECT_ENABLED_CHANNELS}'
